2024-03-21T07:51:51 {"block_run_id": 18486, "block_uuid": "export_to_postgres", "pipeline_run_id": 6163, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "block_type": "data_exporter", "level": "INFO", "message": "Start executing block with BlockExecutor.", "timestamp": 1711007511.781485, "uuid": "84b3a0e9817545c6a53490bdf5a448d1"}
2024-03-21T07:51:51 {"block_run_id": 18486, "block_uuid": "export_to_postgres", "pipeline_run_id": 6163, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "block_type": "data_exporter", "level": "INFO", "message": "Postgres initialized", "timestamp": 1711007511.832867, "uuid": "a6d44e01df3f4fc29e9d8cdfa4b9d7bd"}
2024-03-21T07:51:51 {"block_run_id": 18486, "block_uuid": "export_to_postgres", "pipeline_run_id": 6163, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "block_type": "data_exporter", "level": "INFO", "message": "\u2514\u2500 Opening connection to PostgreSQL database...", "timestamp": 1711007511.833335, "uuid": "a6e4c16e54864b508c42b85a97c7f320"}
2024-03-21T07:51:51 {"block_run_id": 18486, "block_uuid": "export_to_postgres", "pipeline_run_id": 6163, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "block_type": "data_exporter", "level": "INFO", "message": "DONE", "timestamp": 1711007511.841353, "uuid": "6038a60c95f2470aad1ba639b93055a2"}
2024-03-21T07:51:51 {"block_run_id": 18486, "block_uuid": "export_to_postgres", "pipeline_run_id": 6163, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "block_type": "data_exporter", "level": "WARNING", "message": "Exception thrown when attempting to run <function BlockExecutor.execute.<locals>.__execute_with_retry at 0xffffa7db7880>, attempt 1 of 1", "timestamp": 1711007511.841895, "uuid": "521f333f777c4bf1885a4077637803ea", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 588, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1077, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1314, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1223, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1529, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1685, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1724, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 25, in export_data_to_postgres\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/sql.py\", line 279, in export\n    df = clean_df_for_export(df, self.clean, dtypes)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/export_utils.py\", line 90, in clean_df_for_export\n    copy_df = df.copy()\nAttributeError: 'int' object has no attribute 'copy'\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 163, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 743, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 87, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 50, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1643, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 318, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 602, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 28, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 108, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 183, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 288, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 253, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1152, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 613, in execute\n    result = __execute_with_retry()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 46, in retry_func\n    logger.warning(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 39, in warning\n    self.__send_message('warning', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["'int' object has no attribute 'copy'"]}
2024-03-21T07:51:51 {"block_run_id": 18486, "block_uuid": "export_to_postgres", "pipeline_run_id": 6163, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "block_type": "data_exporter", "level": "EXCEPTION", "message": "Failed to execute block export_to_postgres", "timestamp": 1711007511.845928, "uuid": "ac6c0e814a574e79992400abc156e1ac", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 613, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 588, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1077, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1314, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1223, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1529, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1685, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1724, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 25, in export_data_to_postgres\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/sql.py\", line 279, in export\n    df = clean_df_for_export(df, self.clean, dtypes)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/export_utils.py\", line 90, in clean_df_for_export\n    copy_df = df.copy()\nAttributeError: 'int' object has no attribute 'copy'\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 163, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 743, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 87, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 50, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1643, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 318, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 602, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 28, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 108, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 183, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 288, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 253, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1152, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 615, in execute\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["'int' object has no attribute 'copy'"]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 613, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 588, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1077, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1314, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1223, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1529, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1685, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1724, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 25, in export_data_to_postgres
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/sql.py", line 279, in export
    df = clean_df_for_export(df, self.clean, dtypes)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/export_utils.py", line 90, in clean_df_for_export
    copy_df = df.copy()
AttributeError: 'int' object has no attribute 'copy'
2024-03-21T07:57:41 {"block_run_id": 18507, "block_uuid": "export_to_postgres", "pipeline_run_id": 6170, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "block_type": "data_exporter", "level": "INFO", "message": "Start executing block with BlockExecutor.", "timestamp": 1711007861.864283, "uuid": "c98f6a33a1154a7db4fa889b7dd3fd34"}
2024-03-21T07:57:42 {"block_run_id": 18507, "block_uuid": "export_to_postgres", "pipeline_run_id": 6170, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "block_type": "data_exporter", "level": "INFO", "message": "Postgres initialized", "timestamp": 1711007862.044019, "uuid": "ff102fbe12a341d0b0a2ddac95b1d58f"}
2024-03-21T07:57:42 {"block_run_id": 18507, "block_uuid": "export_to_postgres", "pipeline_run_id": 6170, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "block_type": "data_exporter", "level": "INFO", "message": "\u2514\u2500 Opening connection to PostgreSQL database...", "timestamp": 1711007862.044519, "uuid": "93800899bfad4436a6555c49a01fc3ed"}
2024-03-21T07:57:42 {"block_run_id": 18507, "block_uuid": "export_to_postgres", "pipeline_run_id": 6170, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "block_type": "data_exporter", "level": "INFO", "message": "DONE", "timestamp": 1711007862.051956, "uuid": "64ec8d3ab6d24e1ca4a2a4e0c3499d66"}
2024-03-21T07:57:42 {"block_run_id": 18507, "block_uuid": "export_to_postgres", "pipeline_run_id": 6170, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "block_type": "data_exporter", "level": "INFO", "message": "", "timestamp": 1711007862.056532, "uuid": "d3d8e9828b524b589db6764c87a8dfb3"}
2024-03-21T07:57:42 {"block_run_id": 18507, "block_uuid": "export_to_postgres", "pipeline_run_id": 6170, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "block_type": "data_exporter", "level": "INFO", "message": "\u251c\u2500", "timestamp": 1711007862.057017, "uuid": "04081a0ee2cd46a6a0f72b172d2d155c"}
2024-03-21T07:57:42 {"block_run_id": 18507, "block_uuid": "export_to_postgres", "pipeline_run_id": 6170, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "block_type": "data_exporter", "level": "INFO", "message": "\u2514\u2500 Exporting data to 'covid.daily_reports'...", "timestamp": 1711007862.057469, "uuid": "c19a1c288e0f4391b6ab5326097f6f85"}
2024-03-21T07:57:42 {"block_run_id": 18507, "block_uuid": "export_to_postgres", "pipeline_run_id": 6170, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "block_type": "data_exporter", "level": "INFO", "message": "DONE", "timestamp": 1711007862.096124, "uuid": "ebf766c37183482f86312433ad3bdfb1"}
2024-03-21T07:57:42 {"block_run_id": 18507, "block_uuid": "export_to_postgres", "pipeline_run_id": 6170, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "block_type": "data_exporter", "level": "INFO", "message": "Finish executing block with BlockExecutor.", "timestamp": 1711007862.100659, "uuid": "223d120a7bf34516bec9535a0c0330c3"}
2024-03-21T08:00:12 {"block_run_id": 18528, "block_uuid": "export_to_postgres", "pipeline_run_id": 6177, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "block_type": "data_exporter", "level": "INFO", "message": "Start executing block with BlockExecutor.", "timestamp": 1711008012.799207, "uuid": "ff6e7ac1af0540d6b185ac0f74c31415"}
2024-03-21T08:00:12 {"block_run_id": 18528, "block_uuid": "export_to_postgres", "pipeline_run_id": 6177, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "block_type": "data_exporter", "level": "INFO", "message": "Postgres initialized", "timestamp": 1711008012.881358, "uuid": "49365d01e23e4c4fa40c2b2630a367ab"}
2024-03-21T08:00:12 {"block_run_id": 18528, "block_uuid": "export_to_postgres", "pipeline_run_id": 6177, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "block_type": "data_exporter", "level": "INFO", "message": "\u2514\u2500 Opening connection to PostgreSQL database...", "timestamp": 1711008012.881852, "uuid": "7549a027e3e24a7bbff74d063968d598"}
2024-03-21T08:00:12 {"block_run_id": 18528, "block_uuid": "export_to_postgres", "pipeline_run_id": 6177, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "block_type": "data_exporter", "level": "INFO", "message": "DONE", "timestamp": 1711008012.889876, "uuid": "638dbdb4a4da44cf9b21563baf6a2598"}
2024-03-21T08:00:12 {"block_run_id": 18528, "block_uuid": "export_to_postgres", "pipeline_run_id": 6177, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "block_type": "data_exporter", "level": "INFO", "message": "", "timestamp": 1711008012.893713, "uuid": "a3603180771c4239a14910e32f459846"}
2024-03-21T08:00:12 {"block_run_id": 18528, "block_uuid": "export_to_postgres", "pipeline_run_id": 6177, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "block_type": "data_exporter", "level": "INFO", "message": "\u251c\u2500", "timestamp": 1711008012.894152, "uuid": "16a65883b8fb4c80aa765cf00540f1a1"}
2024-03-21T08:00:12 {"block_run_id": 18528, "block_uuid": "export_to_postgres", "pipeline_run_id": 6177, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "block_type": "data_exporter", "level": "INFO", "message": "\u2514\u2500 Exporting data to 'covid.daily_reports'...", "timestamp": 1711008012.894468, "uuid": "9174cfc3932e4e63b8e69741f03969d3"}
2024-03-21T08:00:12 {"block_run_id": 18528, "block_uuid": "export_to_postgres", "pipeline_run_id": 6177, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "block_type": "data_exporter", "level": "INFO", "message": "DONE", "timestamp": 1711008012.935906, "uuid": "df9823f476b94482a915e0d83f13e9ef"}
2024-03-21T08:00:12 {"block_run_id": 18528, "block_uuid": "export_to_postgres", "pipeline_run_id": 6177, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "block_type": "data_exporter", "level": "INFO", "message": "Finish executing block with BlockExecutor.", "timestamp": 1711008012.94028, "uuid": "918d00de8b194871b76bdb2f527703e0"}
